Feature
FrancoRosa/ruby-enumerable pull request #3
Opened 2020-04-01 18:17 UTC by FrancoRosa

In this project:
I built the following methods:
Inside the Enumerable Module
> my_each
> my_each_with_index
> my_select
> my_all?
>  my_any?
> my_none?
> my_count
> my_map
> my_inject

Finally, I made a simple function using _my_inject_

> multiply_els

You can run the tests using:

> $ ruby tests.rb

2020-04-01 20:54 UTC, kobiyoyo requested changes
## Hi @FrancoRosa      ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x] Lets fix stickler errors
- [x] Pull Request should have a meaningful title

- [x] `my_count`
-  returns the number of items in enum through enumeration
`p [8,87,6,5].my_count` should return `4`
- counts the number of items in enum that are equal to item if an argument is given:
`p  [1, 2, 3].my_count(2)` should return `1`
-  counts the number of elements yielding a true value if a block is given
`block = proc { |num| num < (2 + 24) / 2 }`
`p [23,13,12,43].my_count(&block)` should return 1

- [x] `my_inject`:
- Combines all elements of enum by applying a binary operation, specified by a block:
`search = proc { |memo, word| memo.length > word.length ? memo : word } `
`p ['hello','strong','am'].inject(&search)` should return `strong`
- [x] `my_none?`:
- When a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
`p ['hello'].my_none?(5)` - should return `true`
- [x] `my_any?`:
- when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
`p ['cat',2,32,].my_any?('cat')` should return `true`
- [x] `my_all`  
- when no block or argument is given returns true when none of the collection members are false or nil:
 `p [1, true, 'hi', []].my_all?` should return `true`.
- when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
`p [3,3,3,3].my_all?(3)` should return `true`



### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-04-02 23:49 UTC, kobiyoyo requested changes
## Hi @FrancoRosa    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, you are almost there .
### General

- [x] `my_all`  
- when no block or argument is given returns true when none of the collection members are false or nil:
`p [1, true, 'hi',false].my_all?` should return `false`
- [x] `my_inject`:
- When a symbol is specified combines each element of the collection by applying the symbol as a named method
`p (5..10).my_inject(:*)` should return `151200`

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-04-05 16:58 UTC, pelzolga123 commented
## Hi Franco,
### Good job so far :+1:  just a few changes left: 

* [ ] `[1, true, 'hi', []].my_all?` should return the same result as original ruby method: `[1, true, 'hi', []].all?` 
* [ ] Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-04-05 16:59 UTC, pelzolga123 commented on .rubocop.yml
> +    - "tests.rb"
Do not make any changes in config files.

2020-04-05 17:00 UTC, pelzolga123 commented on .rubocop.yml
> +  Max: 30
Do not make any changes in config files

2020-04-05 17:00 UTC, pelzolga123 commented on .rubocop.yml
> +  Max: 180
Do not make any changes in config files

2020-04-06 12:21 UTC, majovanilla requested changes
Hey @FrancoRosa , 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯

## You just have ONE thing to change and submit your request again! 😀

Please check the comment below on you code.

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-04-06 12:21 UTC, majovanilla commented on scripts.rb
> +      arr.my_each { |k| mem = mem.send(args[0], k) }
This piece of code is not working. When I run `[1,2,3,4,5].my_inject(:+)` on your project, I get the wrong sum!

2020-04-06 17:48 UTC, kobiyoyo requested changes
## Hi @FrancoRosa     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works well but i cant approve this project until everything is fine with the stickler  
### General
- [ ] Please fix the stickler 
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-04-06 19:46 UTC, shshamim63 commented
## Status :100:  Approved :100: 
___
Hi @FrancoRosa :wave: ,
Awesome job :clap:, You have covered all the changes asked by the previous reviewer. And you have changed the rubocop.yml file cause of the new release, I understand. But it is always better to add comments if you need to update the crucial files like stickler and robocop.
____
##### This :+1:  is from me. You can go ahead and merge it now.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Twitter](https://twitter.com/Shshamim090)

2020-04-06 20:15 UTC, merged